### ISSUE TITLE
App Engine service URLs "/ah/*" changed to "/_ah/*"

### ISSUE THREAD

**Issue by phorward** [viur-framework/server#158]
Hello,
today I had a strange problem with my project, which came up when I tried to upload a file from my app into itself using the following function as extension to the File module:
```python
def write(self, filename, content, mimetype = "text/plain"):
	"""
	Write a file into the file module.

	:param filename: Filename to be written.
	:param content:  File content.
	:param mimetype: The file's mimetype.

	:return: Returns the key of the file object written.
	"""
	res = requests.post(
		blobstore.create_upload_url("/json/file/upload"),
		data={"skey": securitykey.create()},
		files={"file": (filename, content, mimetype)},
		timeout=60
	)

	if res.ok:
		res = res.json()
		assert res["action"] == "addSuccess"

		return res["values"][0]["key"]

	return None
```
Because `conf["viur.forceSSL"] = True` is now set by default in the current develop branch, the server redirects the request to "/_ah/upload" to the https-base-url, so the requested answer is a HTML-site that wants the "user" to login.

You can see this in this anonymised log-snippet:
```
2019-04-24 11:11:44.726 CEST Downloading https://myproject-viur.appspot.com/file/download/AMIfv942JSDtCmgk41KSP0mY97lSfZiENRu004lP0vvJDpE2k8W2mLEhvWnwwTIXIucXlBxiG-MJdIF09nM8ouLZvFOs5WihIPVtq3T3cUc2OdyYuqqezMzICvq8P8xJN-AJOo_0bGmTtfhsc4dJNBU8-xxRXezgRMKQ0oLWHnQff9gKZWdiaX0 (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/importer.py:165)
2019-04-24 11:11:44.726 CEST GET  https://myproject-viur.appspot.com/vi/file/download/AMIfv942JSDtCmgk41KSP0mY97lSfZiENRu004lP0vvJDpE2k8W2mLEhvWnwwTIXIucXlBxiG-MJdIF09nM8ouLZvFOs5WihIPVtq3T3cUc2OdyYuqqezMzICvq8P8xJN-AJOo_0bGmTtfhsc4dJNBU8-xxRXezgRMKQ0oLWHnQff9gKZWdiaX0 {'timeout': 60} (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/importer.py:70)
2019-04-24 11:11:44.808 CEST "GET /vi/file/download/AMIfv942JSDtCmgk41KSP0mY97lSfZiENRu004lP0vvJDpE2k8W2mLEhvWnwwTIXIucXlBxiG-MJdIF09nM8ouLZvFOs5WihIPVtq3T3cUc2OdyYuqqezMzICvq8P8xJN-AJOo_0bGmTtfhsc4dJNBU8-xxRXezgRMKQ0oLWHnQff9gKZWdiaX0 HTTP/1.1" 404 None (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:344)
2019-04-24 11:11:44.809 CEST Download failed, trying to fetch using servingurl u'https://lh3.googleusercontent.com/o2S7xVKqmVIWE48n831DSmnBbVdZV-S-SDNUrERG5nz9HjwWXVv8hg05UvsC3UKWXthKU3OleU7iqiVuKLB92BRXbg' (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/importer.py:169)
2019-04-24 11:11:44.811 CEST Starting new HTTPS connection (1): lh3.googleusercontent.com (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:633)
2019-04-24 11:11:44.821 CEST "GET /o2S7xVKqmVIWE48n831DSmnBbVdZV-S-SDNUrERG5nz9HjwWXVv8hg05UvsC3UKWXthKU3OleU7iqiVuKLB92BRXbg HTTP/1.1" 200 None (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:344)
2019-04-24 11:11:44.822 CEST u'168 - Sicherheitsglas Tropfen hell.jpg' has 24557 bytes (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/importer.py:177)
2019-04-24 11:11:44.899 CEST Starting new HTTP connection (1): myprojectdev-viur.appspot.com (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:176)
2019-04-24 11:11:49.252 CEST "POST /_ah/upload/AMmfu6Yur14OrwuFnZjMoa1JJbov808Piy0fqM3oICZTpO5R702qI_QErou075OgTi9v99Q5f0op7C-XmTz0zK1Dgp9UvwzeoDycKNjX_GlT0PzhGBFJq24_IORI72BQTKfPpOuFYSJIfhqObl2T56LglPY3OLoGR7LZn5ITPkkannrOqoY0ul3fgA3t9SXJCz1zMLabU2TyOmVeP5An89cYMEUnrlvrPZCwnqX_9fx01FG0WX59aCs/ALBNUaYAAAAAXMAqqLaL8LuETRDqzfRkphDsuNVK44xR/ HTTP/1.1" 302 None (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:344)
2019-04-24 11:11:49.254 CEST Starting new HTTPS connection (1): myprojectdev-viur.appspot.com (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:633)
2019-04-24 11:11:49.415 CEST "GET / HTTP/1.1" 302 None (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:344)
2019-04-24 11:11:49.417 CEST Starting new HTTPS connection (1): login.myproject.de (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:633)
2019-04-24 11:11:49.550 CEST
"GET /?portal=myprojectdev HTTP/1.1" 302 None (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:344)
2019-04-24 11:11:49.850 CEST
"GET /user/auth_userpassword/login?portal=myprojectdev HTTP/1.1" 200 None (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:344)
2019-04-24 11:11:49.852 CEST
No JSON object could be decoded (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/server/tasks.py:151)
Traceback (most recent call last):
  File "/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/server/tasks.py", line 147, in deferred
    caller(*args, **kwargs)
  File "/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/server/tasks.py", line 318, in <lambda>
    return( lambda *args, **kwargs: mkDefered( func, *args, **kwargs) )
  File "/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/server/tasks.py", line 280, in mkDefered
    return func(self, *args, **kwargs)
  File "/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/prototypes/importable.py", line 137, in doImport
    ret = imp.toSkel(skel, values, tr, sourceKey = "key" if "key" in values else "id")
  File "/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/importer.py", line 441, in toSkel
    changes += self.translate(skel, values, translate)
  File "/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/importer.py", line 394, in translate
    changes += self.setSkelValue(skel, tr, values[bone])
  File "/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/importer.py", line 227, in setSkelValue
    key = self.importFile(entry["dest"])
  File "/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/importer.py", line 179, in importFile
    key = conf["viur.mainApp"].file.write("file", content, mimetype)
  File "/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/modules/file.py", line 50, in write
    res = res.json()
  File "/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/models.py", line 733, in json
    return json.loads(self.text, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_dist/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_dist/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/7679791231c143f9/python27/python27_dist/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
I can't explain the concrete reasons why this project behaves here this way, but what I can say is, that the default ViUR whitelist currently is `conf["viur.noSSLCheckUrls"]` currently contains `["/_tasks*", "/ah/*"]` but should be `["/_tasks*", "/_ah/*"]` to work properly as expected and avoid such problems.

**Comment by phorward** [comment]
Further examination: The problem in above log file are these two lines.
```
2019-04-24 11:11:44.899 CEST Starting new HTTP connection (1): myprojectdev-viur.appspot.com (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:176)
2019-04-24 11:11:49.252 CEST "POST /_ah/upload/AMmfu6Yur14OrwuFnZjMoa1JJbov808Piy0fqM3oICZTpO5R702qI_QErou075OgTi9v99Q5f0op7C-XmTz0zK1Dgp9UvwzeoDycKNjX_GlT0PzhGBFJq24_IORI72BQTKfPpOuFYSJIfhqObl2T56LglPY3OLoGR7LZn5ITPkkannrOqoY0ul3fgA3t9SXJCz1zMLabU2TyOmVeP5An89cYMEUnrlvrPZCwnqX_9fx01FG0WX59aCs/ALBNUaYAAAAAXMAqqLaL8LuETRDqzfRkphDsuNVK44xR/ HTTP/1.1" 302 None (/base/data/home/apps/e~myprojectdev-viur/2019-04-24-jm.417711575748734341/lib/requests/packages/urllib3/connectionpool.py:344)
```
`blobstore.create_upload_url()` still generates a non-https-URL, and regarding the (poor) docs on these function, there is no way to specify secure connection via parameter or something else. The "/_ah/upload" is generated from this function.

**Comment by tsteinruecken** [comment]
AFAIK the scheme (http or https) returned from create_upload_url() matches the scheme of the request that's calls it. If create_upload_url is called inside a request that arrived over https you should get an https url in return. Did you call create_upload_url inside a deferred task? The callbacks from task-queue are http only, so you'll always get an insecure upload_url in return. Solution is to issue a url-fetch to /file/getUploadURL over https to get a correct one.

**Comment by phorward** [comment]
> Did you call create_upload_url inside a deferred task? The callbacks from task-queue are http only, so you'll always get an insecure upload_url in return. Solution is to issue a url-fetch to /file/getUploadURL over https to get a correct one.

Correct, it comes from a deferred tasks. So I should call self.getUploadURL() in this case or make a request there? Why should this work? Can you please provide an example?

**Comment by tsteinruecken** [comment]
This has been resolved for the specific project using a url-fetch over https to itself, and as this won't be an issue in 3.x due to the move to GCS i'll close this issue.
